# -*- eval: (cargo-minor-mode 1) -*-

[package]
name = "tg2mx-bot"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
dotenvy = "0.15"
futures-util = "0.3"
heck = "0.4.1"
indexmap = { version = "2.0", features = ["serde"] }
indoc = "2.0"
log = "0.4"
monostate = "0.1"
mstickerlib = "0.1"
once_cell = "1.9"
pretty_env_logger = "0.5"
reqwest = { version = "0.11", features = ["gzip", "json", "rustls-tls-webpki-roots"], default-features = false }
ruma = "0.9.2"
serde = { version = "1.0.184", features = ["derive"] }
serde-big-array = "0.5"
serde_json = "1.0"
tokio = { version = "1.20", features = ["macros", "rt-multi-thread", "sync", "time"] }
tracing = { version = "0.1", features = ["log"] }

[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "e5b06bd6d81597b4402d82d14cc4f1650ad8fc05"
features = ["rustls-tls"]
default-features = false
