name: Rust

on:
  push:
    branches: [main]
    tags:
  pull_request:
  release:
    types: [created]
  workflow_dispatch:

env:
  RUST_BACKTRACE: "1"
  RUST_LOG: "info"
  # speed up build by using clang/lld
  CC: "clang"
  CXX: "clang++"
  LD: "clang"
  LDFLAGS: "-fuse-ld=lld"
  RUSTFLAGS: "-C linker=clang -C link-arg=-fuse-ld=lld"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        rust:
          - toolchain: "stable"
          - toolchain: "nightly"
    name: "Test (Rust ${{matrix.rust.toolchain}})"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msrd0/install-rlottie-action@v1
      - run: sudo apt update -y && sudo apt install -y libavdevice-dev
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{matrix.rust.toolchain}}"
        id: "rust-toolchain"
      
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: "${{runner.os}} Rust ${{steps.rust-toolchain.outputs.cachekey}}"
      
      - run: cargo test --workspace --locked

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all --check
